# Generated by Django 2.2.24 on 2022-03-23 18:49
import phonenumbers
from django.db import migrations


def clear_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = phonenumbers.parse(
            flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(flat.owner_pure_phone):
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20220323_2141'),
    ]

    operations = [
        migrations.RunPython(clear_phones),
    ]
