# Generated by Django 2.2.24 on 2022-03-23 20:06

from django.db import migrations


def set_owner_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all().iterator():
        flats_set = Flat.objects.filter(
            owner=owner.full_name,
            owners_phonenumber=owner.owners_phonenumber
        )
        owner.flats.set(flats_set)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220323_2318'),
    ]

    operations = [
        migrations.RunPython(set_owner_flats),
    ]
